name: main

on:
  push:
    branches: [ main ]

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
        env:
          RUSTFLAGS: "-Dwarnings"
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: docker push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bragecrew/barger:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.DOCKER_TOKEN }}
