name: main

on:
  push:
    branches: [ main ]

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
        env:
          RUSTFLAGS: "-Dwarnings"
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: docker/build-push-action@v2
