name: main

on:
  push:
    branches: [ main ]

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: rust cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: rust clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
        env:
          RUSTFLAGS: "-Dwarnings"
      - name: rust build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: rust test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: docker buildx
        uses: docker/setup-buildx-action@v1
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: bargecrew
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: docker cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: docker push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bargecrew/barger:latest
